#!/bin/bash -eu

# PS:1 Puppet Configuration
# Use librarian-puppet to reload modules. 
# Fun Fact, this is the install script. 

apt-get install -y puppet puppetmaster rubygems
gem install librarian-puppet hiera 
gem install --pre hiera-puppet
cd /etc/puppet
librarian-puppet update
/etc/init.d/puppetmaster restart
/etc/init.d/puppet restart

